Extract operation name and type from execution context
strawberry-graphql/strawberry pull request #1286
Opened 2021-10-01 13:18 UTC by jkimbo

## Description

Add properties to ExecutionContext to extract the operation name and type from the graphql document.

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-10-01 13:20 UTC, botberry commented
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Jonathan Kim for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```
<!-- action-check: release-file -->

2021-10-01 16:11 UTC, BryceBeagle requested changes

2021-10-01 16:11 UTC, BryceBeagle commented on strawberry/types/execution.py
> +    _provided_operation_name: Optional[str] = None
Maybe we can use [`InitVar`](https://docs.python.org/3/library/dataclasses.html#init-only-variables)

2021-10-01 16:11 UTC, BryceBeagle commented on strawberry/types/execution.py
> +        )
Above, in the `operation_type` properly, you used a for loop with a `break` for a very similar operation. Suggest using the same technique for both

2021-10-02 13:22 UTC, jkimbo commented on strawberry/types/execution.py
> +    _provided_operation_name: Optional[str] = None
Yep agreed.

2021-10-10 09:42 UTC, jkimbo commented
@BryceBeagle @patrick91 this is ready for review again.

2021-12-07 12:38 UTC, patrick91 approved these changes

2021-12-07 14:35 UTC, patrick91 commented on RELEASE.md
> +Release type: patch
```suggestion
Release type: minor
```

2021-12-07 15:02 UTC, merged