Improve type checker support for return value for strawberry.union
strawberry-graphql/strawberry pull request #1438
Opened 2021-11-23 12:37 UTC by patrick91

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-11-23 12:47 UTC, botberry commented
Thanks for adding the `RELEASE.md` file!

![](https://media.giphy.com/media/xq1FxHkABwW7m/giphy.gif)

Here's a preview of the changelog:

---

This release improves type checking support for `strawberry.union` and now allows
to use unions without any type issues, like so:

```python
@strawberry.type
class User:
    name: str

@strawberry.type
class Error:
    message: str

UserOrError = strawberry.union("UserOrError", (User, Error))

x: UserOrError = User(name="Patrick")
```


---
Here's the preview release card for twitter:

![](https://i.imgur.com/kBy4mnw.png)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Patrick Arminio for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```
<!-- action-check: release-file -->

2021-11-23 16:04 UTC, BryceBeagle requested changes

2021-11-23 16:04 UTC, BryceBeagle commented on strawberry/union.py
> +) -> Union[Types]:  # type: ignore
Add a comment explaining that the typing of `types` is perfect right now, but will change in the future with [Variadic Generics](https://www.python.org/dev/peps/pep-0646/).

2021-11-26 12:13 UTC, patrick91 commented on RELEASE.md
> +to use unions without any type issues, like so:
```suggestion
to use unions without any type issue, like so:
```

2021-11-26 15:49 UTC, merged