Move enum deserialization logic from convert_arguments to CustomGraph…
strawberry-graphql/strawberry pull request #1765
Opened 2022-03-25 00:04 UTC by paulo-raca

## Description

Apparently Python's GraphQL core enum isn't designed to work with Python Enums out of the box :man_facepalming:.

Instead, strawberry defines custom serialization/deserialization logic. However it is currently split in 2 places:
  - `CustomGraphQLEnumType` takes care of converting an enum object to it's value during _serialization_ (Which is later converted to its name by GraphQL Core)
  - `convert_arguments` converts the enum value back to the enum object during _deserialization_

This PR moves the deserialization step into `CustomGraphQLEnumType`, which has a few (minor) advantages:
- Both are kept together in source
- deserialization is automatically triggered in GraphQL-Core instead of being handled explicitly
  - (This makes it a little simpler to hack strawberry types for serialization/deserialization -- A thing I'm working on)

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Documentation

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.  (Not necessary)
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2022-03-25 00:07 UTC, botberry commented
Thanks for adding the `RELEASE.md` file!

![](https://media.giphy.com/media/xq1FxHkABwW7m/giphy.gif)

Here's a preview of the changelog:

---

Refactoring: Move enum deserialization logic from convert_arguments to CustomGraphQLEnumType


---
Here's the preview release card for twitter:

![](https://i.imgur.com/Oy9COgo.png)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to Paulo Costa for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```
<!-- action-check: release-file -->

2022-04-03 18:12 UTC, BryceBeagle requested changes

2022-04-03 18:12 UTC, BryceBeagle commented on strawberry/schema/schema_converter.py
> +        return self.wrapped_cls(super().parse_value(input_value))
Can you add coverage tests here? Otherwise, lgtm :+1:

2022-04-11 01:50 UTC, BryceBeagle approved these changes

2022-04-20 18:58 UTC, patrick91 approved these changes

2022-04-20 18:58 UTC, merged