Add simple awaitable channel_listen
strawberry-graphql/strawberry pull request #2856
Opened 2023-06-16 10:14 UTC by moritz89

Why:

- Allow user code to be run after Channels subscription
- Avoids race condition when confirming GQL subscriptions

This change addresses the need by:

- Returning the async generator instead of runnning it

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-06-16 10:14 UTC, moritz89 commented
Addresses issue #2799

2023-06-16 10:16 UTC, botberry commented
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)


Here's the tweet text: 
```
🆕 Release (next) is out! Thanks to @moritz89 for the PR 👏

Get it here 👉 https://github.com/strawberry-graphql/strawberry/releases/tag/(next)
```
<!-- action-check: release-file -->

2023-06-16 10:17 UTC, moritz89 commented
This is the simplest implementation possibility. However, it has the problem that a leak can occur if the async generator is never started. Will create a second approach that uses a context manager to ensure that the cleanup will be done.

2023-06-16 10:30 UTC, moritz89 commented
Added a second option of starting channel_listen with a context manager to ensure that group_discard is called after it is started.

2023-06-19 09:56 UTC, moritz89 commented
@DoctorJohn @patrick91 Wanted to ask which approach you'd prefer? ContextManager or the simple approach

2023-06-21 18:16 UTC, DoctorJohn commented
> @DoctorJohn @patrick91 Wanted to ask which approach you'd prefer? ContextManager or the simple approach

Hi @moritz89 thanks for the PR. I prefer the ContextManager approach. It's the one I did my quick proof of concept with. Main argument for it is the cleanup ability you already mentionened in your comment. Feel free to remove the "simple approach".

2023-06-22 14:41 UTC, moritz89 commented
Isn't this fun, adding breaking changes :sweat_smile: Anything else that should be updated?

2023-06-22 14:43 UTC, patrick91 commented
@moritz89 it is a lot of work to make it backwards compatibile with a deprecation? 😊

2023-06-22 14:52 UTC, moritz89 commented
> @moritz89 it is a lot of work to make it backwards compatibile with a deprecation? blush

Not at all. The question is only how this should be handled. It would result in two functions in the API and the question is how they should be named. One option is to append `_ctx` to the new function.

2023-06-24 10:10 UTC, moritz89 commented
@patrick91 I've had a look at unifying the calls in the following style, but also that did not work and going down that line of thought makes the library code itself more and more tricky. If you have any suggestions, would be glad to take them up.

```
class ChannelListen:
    def __init__(
        self, type: str, *, timeout: Optional[float] = None, groups: Sequence[str] = ()
    ) -> None:
        ...

    async def __call__(
        self, type: str, *, timeout: Optional[float] = None, groups: Sequence[str] = ()
    ) -> Any:
        ...

    async def __aenter__(self) -> Awaitable[AsyncGenerator[Any, None]]:
        ...

    async def __aexit__(self) -> None:
        ...

    async def _channel_listen_generator(
        self, queue: asyncio.Queue, timeout: Optional[float]
    ) -> AsyncGenerator[Any, None]:
        ...

class ChannelsConsumer(AsyncConsumer):
    ...
    channel_listen = ChannelListen
```

2023-06-24 13:42 UTC, moritz89 commented
Fixed mypy issues and updated existing tests and added a new one, but don't know why one is failing:

`ERROR 😡  tests/cli/test_server.py::test_debug_server_routes - KeyError: 'STRAWBERRY_DEBUG_SERVER_SCHEMA'`

Would appreciate help in fixing it

2023-06-27 15:13 UTC, moritz89 commented
How should the deprecation be communicated to the library users?

2023-06-27 15:23 UTC, DoctorJohn commented
> I'll create a commit assuming you meant the former (deprecate the existing approach).

Yup, that's what I meant. I think the new approach is superior and covers all usecases of the old one.

> How should the deprecation be communicated to the library users?

Using the `warnings` module, just like here for example:

https://github.com/strawberry-graphql/strawberry/blob/19be5751c888bea76c03401be105a4a1b80c723c/strawberry/types/info.py#L52-L56

2023-06-27 16:24 UTC, moritz89 commented
@patrick91 The MR won't break compatibility but adds a deprecation warning

2023-06-27 16:36 UTC, DoctorJohn requested changes

2023-06-27 16:36 UTC, DoctorJohn commented on docs/integrations/channels.md
> +                    )
These docs need an update now :)

```suggestion
        async with ws.listen_to_channel("chat.message", groups=room_ids) as cm:
            async for message in cm:
                if message["room_id"] in room_ids:
                    yield ChatRoomMessage(
                        room_name=message["room_id"],
                        message=message["message"],
                        current_user=user,
                    )
```

2023-06-27 16:36 UTC, DoctorJohn commented on docs/integrations/channels.md
> +a single websocket connection. The `ws.channel_listen` context manager will return
```suggestion
a single websocket connection. The `ws.listen_to_channel` context manager will return
```

Here as well :)

2023-06-27 16:36 UTC, patrick91 commented
> @patrick91 The MR won't break compatibility but adds a deprecation warning

Thank you so much! <3

2023-07-03 15:11 UTC, moritz89 commented
@DoctorJohn @patrick91 Does this MR require anything else or can it be merged?

2023-07-03 15:17 UTC, patrick91 commented on strawberry/channels/handlers/base.py
> +            )
👍

2023-07-03 15:54 UTC, moritz89 commented on RELEASE.md
> +      yield None
It's to show how GQL subscription confirmations (with null data) should be migrated, i.e., that confirmation messages should be sent before the `async for` loop. However, for every else not confirming their GQL subscriptions the `yield None` can be omitted in both new and old code variants.

How should the doc be updated to reflect that?

2023-07-03 18:31 UTC, moritz89 commented on RELEASE.md
> +      yield None
Good point. Added a section in the channels.md doc

2023-07-04 14:04 UTC, merged

2023-07-04 14:04 UTC, botberry commented
Thanks for contributing to Strawberry! 🎉 You've been invited to join
the Strawberry GraphQL organisation 😊

You can also request a free sticker by filling this form: https://forms.gle/dmnfQUPoY5gZbVT67

And don't forget to join our discord server: https://strawberry.rocks/discord 🔥