docs: updated federation guide to include federation-specific graphql…
strawberry-graphql/strawberry pull request #3145
Opened 2023-10-10 21:51 UTC by bradleyoesch

Updated federation guide to include [Federation-specific GraphQL directives](https://www.apollographql.com/docs/federation/federated-types/federated-directives).

## Description

I didn't realize there were federated schema directives already implemented in strawberry! Updated documentation to make it easier to find.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* Closes #3134

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2023-10-10 22:20 UTC, bradleyoesch commented
Please leave any comments to clarify/change/update/etc!

2023-11-08 15:05 UTC, DoctorJohn requested changes
Well written as well, thanks so much @bradleyoesch! I left some small comments which could give this PR it's final touch.

2023-11-08 15:05 UTC, DoctorJohn commented on docs/guides/federation.md
> +For example:
nit:

```suggestion
For example, adding the following directives:
```

2023-11-08 15:05 UTC, DoctorJohn commented on docs/guides/federation.md
> +Will result in:
nit:

```suggestion
Will result in the following GraphQL schema:
```

2023-11-15 19:57 UTC, bradleyoesch commented
> Well written as well, thanks so much @bradleyoesch! I left some small comments which could give this PR it's final touch.

@DoctorJohn Thanks! I committed the suggestions

2023-11-16 15:59 UTC, DoctorJohn approved these changes
Awesome, thanks again for the PR! LGTM

2023-11-16 16:02 UTC, patrick91 approved these changes

2023-11-16 16:02 UTC, merged