Add some runtime checking for unions
strawberry-graphql/strawberry pull request #575
Opened 2020-11-17 18:49 UTC by jkimbo

## Description

Fixes #571

Not sure whether it's worth creating specific Strawberry exceptions for this cases. What do you think @patrick91 ?

## Types of Changes

- [x] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #571

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-11-17 18:50 UTC, botberry commented
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)
<!-- action-check: release-file -->

2020-11-17 18:55 UTC, jkimbo commented
Not sure why codecov thinks this change will reduce code coverage...

2020-11-17 19:03 UTC, BryceBeagle commented on tests/types/test_union.py
> +    with pytest.raises(Exception, match="No types passed to `union`"):
TIL `match` argument. I will have to use this in the future.

2020-11-17 19:05 UTC, BryceBeagle requested changes
Should we create custom exceptions (i.e. in `strawberry.exceptions`) for these?

2020-11-17 21:14 UTC, jkimbo commented
> Should we create custom exceptions (i.e. in `strawberry.exceptions`) for these?

I was wondering about that. Happy to do so though I can't see developers wanting to catch specific exceptions. Also I think the `len(types)` check should probably stay as a TypeError.

2020-11-17 21:16 UTC, patrick91 commented
> Should we create custom exceptions (i.e. in `strawberry.exceptions`) for these?

Good question!

My idea around exception was that at some point we'd have a way to link to the docs for some of them[1], especially the ones that maybe don't make a lot of sense to a beginner :)

[1] Via a custom __repr__ or something :)

2020-11-17 21:17 UTC, BryceBeagle commented
> Also I think the len(types) check should probably stay as a TypeError

Technically speaking, our custom exception could just extend `TypeError`

2020-11-17 22:44 UTC, jkimbo commented
> My idea around exception was that at some point we'd have a way to link to the docs for some of them[1], especially the ones that maybe don't make a lot of sense to a beginner :)

I like this reasoning around when to add custom exceptions. Will update the PR with some.

2020-11-18 15:06 UTC, patrick91 approved these changes
Perfect, I was struggling understanding why we changed the test, but the I noticed the test was wrong 🤣 nice one!

2020-11-18 15:06 UTC, merged