Update pyproject.toml
strawberry-graphql/strawberry pull request #641
Opened 2020-12-26 23:15 UTC by tbarnier

## Description

Since version 3.1.0, `graphql.utilities.schema_printer` has been renamed `graphql.utilities.print_schema` causing import errors

## Types of Changes

- [ ] Core
- [X] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

* #626

## Checklist

- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-12-26 23:16 UTC, botberry commented
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)
<!-- action-check: release-file -->

2020-12-27 11:12 UTC, jkimbo requested changes
Thanks! If you could revert the strawberry version bump and add a release file then we can get this merged.

2020-12-27 11:12 UTC, jkimbo commented on pyproject.toml
> +version = "0.44.4"
You don't need to bump the version manually here. The deployment pipeline will automatically increment the version number if you add a Release file.

2021-01-02 12:20 UTC, patrick91 approved these changes
This looks great @tbarnier, would be able to add a release file and amend the version as @jkimbo suggested? :)

2021-01-20 22:50 UTC, patrick91 approved these changes

2021-01-20 22:53 UTC, patrick91 commented
@tbarnier I took the liberty of finishing this PR, thanks for reporting the issue and sending the PR 😊

2021-01-20 22:53 UTC, merged