Enable .(dot) notaion in the get_context of the django views.
strawberry-graphql/strawberry pull request #723
Opened 2021-02-25 10:58 UTC by ernestoarbitrio

## Description
Currently the request coming from the `context` object within the `get_context`  in `views.py` in the `django` module, is a dict which can be accessed via standard python syntax. This PR adds the dot notation to the `request` object.
```python3
>>> context = {"request": "hi"}
>>> print(context.request)
hi
>>> print(context["request"]
hi
```
__Note: this works with nested dict too__

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [X] Enhancement/optimization
- [ ] Documentation

## Checklist

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the CONTRIBUTING document.
- [X] I have added tests to cover my changes.
- [X] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-02-25 15:29 UTC, BryceBeagle requested changes

2021-02-25 15:29 UTC, BryceBeagle commented on RELEASE.md
> +Release type: enhancement
The release type should be `patch`, `minor`, or `major`. This is used to bump the version number:

https://github.com/strawberry-graphql/strawberry/blob/772703c7c47173eeb9e4e8d4c43fccd28166d520/.github/release-check-action/release.py#L14-L17

2021-02-28 15:03 UTC, patrick91 approved these changes
Nice one, looks good to me! I'll fix a typo and then merge 😊

2021-02-28 15:03 UTC, patrick91 commented on strawberry/django/context.py
> +    def __getitem__(self, key):
just adding a note for future people, we are adding this so that we don't break old code that's using `info.context["request"]`

2021-02-28 15:03 UTC, patrick91 commented on tests/django/test_views.py
> +class GetRequestValueWithDotNotaionQuery:
```suggestion
class GetRequestValueWithDotNotationQuery:
```

2021-02-28 15:03 UTC, patrick91 commented on tests/django/test_views.py
> +    "query", (GetRequestValueWithDotNotaionQuery, GetRequestValueQuery)
```suggestion
    "query", (GetRequestValueWithDotNotationQuery, GetRequestValueQuery)
```

2021-02-28 15:17 UTC, merged