Use custom json encoder to prevent encoding error
strawberry-graphql/strawberry pull request #728
Opened 2021-02-28 20:42 UTC by patrick91

## Description

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Documentation

## Issues Fixed or Closed by This PR

*

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes.
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-03-05 13:42 UTC, botberry commented
Thanks for adding the `RELEASE.md` file!

![](https://media.giphy.com/media/xq1FxHkABwW7m/giphy.gif)

Here's a preview of the changelog:

---

This release fixes a bug when using the debug server and upload a file

<!-- action-check: release-file -->

2021-03-05 16:20 UTC, BryceBeagle requested changes

2021-03-05 16:20 UTC, BryceBeagle commented on strawberry/utils/debug.py
> +from typing import Any
This file now uses both `Any` and `typing.Any`. Probably want to make that consistent

2021-03-08 15:30 UTC, BryceBeagle approved these changes

2021-03-09 20:12 UTC, merged