Added JSONScalar example to docs
strawberry-graphql/strawberry pull request #958
Opened 2021-05-20 10:27 UTC by Speedy1991

Added example for a JSON scalar to the docs

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [x] Documentation

## Checklist

- [ ] My code follows the code style of this project.  -> Only a documentation change
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [ ] I have added tests to cover my changes. -> Only a documentation change
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage).  -> Only a documentation change

2021-05-22 14:09 UTC, botberry commented
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/),so make sure to pick the appropriate type. If in doubt feel free to ask :)
<!-- action-check: release-file -->

2021-05-22 14:13 UTC, BryceBeagle requested changes
Just a minor formatting change :+1:

2021-05-22 14:13 UTC, BryceBeagle commented on docs/types/scalars.md
> +    "someNumbers": [1,2, 3]
```suggestion
    "someNumbers": [1, 2, 3]
```

2021-05-23 06:42 UTC, jkimbo requested changes

2021-05-23 06:42 UTC, jkimbo commented on docs/types/scalars.md
> +    def data(self, info) -> GenericScalar:
```suggestion
    def data(self, info) -> JSONScalar:
```

2021-05-23 06:42 UTC, jkimbo commented on docs/types/scalars.md
> +```
In the docs we have a custom language that presents queries and responses side by side (for example https://strawberry.rocks/docs/guides/errors#graphql-validation-errors). So this code example can become:

```suggestion
```graphql+response
query ExampleDataQuery {
  data
}
---
{
  "data": {
    "hello": {
      "a": 1
    },
    "someNumbers": [1, 2, 3]
  }
}
```
```

2021-05-23 07:48 UTC, Speedy1991 commented
Added the requested changes. Is the Bot Release.md comment important? I'm not sure if/what I should add to this file?

2021-05-23 08:35 UTC, jkimbo commented
@Speedy1991 don't worry about the release file. It's for code changes not doc changes.

2021-05-23 08:35 UTC, jkimbo approved these changes

2021-05-23 08:39 UTC, merged

2021-05-23 08:39 UTC, jkimbo commented
Thanks @Speedy1991 ! Signup for a sticker: https://forms.gle/dmnfQUPoY5gZbVT67