Add file list upload support
strawberry-graphql/strawberry pull request #979
Opened 2021-05-31 18:55 UTC by DoctorJohn

## Description

This PR adds support for uploading lists of files (`[Upload!]!`) to all integrations.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [x] New feature
- [x] Enhancement/optimization
- [x] Documentation

## Issues Fixed or Closed by This PR

* Fixes #766 

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2021-05-31 18:56 UTC, botberry commented
Hi, thanks for contributing to Strawberry 🍓!

We noticed that this PR is missing a `RELEASE.md` file. We use that to automatically do releases here on GitHub and, most importantly, to PyPI!

So as soon as this PR is merged, a release will be made 🚀.

Here's an example of `RELEASE.md`:

```markdown
Release type: patch

Description of the changes, ideally with some examples, if adding a new feature.
```

Release type can be one of patch, minor or major. We use [semver](https://semver.org/), so make sure to pick the appropriate type. If in doubt feel free to ask :)
<!-- action-check: release-file -->

2021-06-01 13:59 UTC, BryceBeagle requested changes
This looks great :+1:

2021-06-01 13:59 UTC, BryceBeagle commented on strawberry/file_uploads/utils.py
> +) -> Dict[str, Any]:
```suggestion
def replace_placeholders_with_files(
    operations_with_placeholders: Dict[str, Any],
    files_map: Mapping[str, List[str]],
    files: Mapping[str, Any],
) -> Dict[str, Any]:
```

2021-06-01 15:30 UTC, BryceBeagle approved these changes

2021-06-01 16:46 UTC, patrick91 approved these changes
Wow, this looks great! I'll merge it now 😊

2021-06-01 16:46 UTC, patrick91 commented on docs/guides/file-upload.md
> +## Sanic / Flask / Django / AIOHTTP
💯

2021-06-01 16:46 UTC, merged